test: SDL_Tetris.cpp Button.cpp Game.cpp Matrix.cpp Shape.cpp TextTexture.cpp Utility.cpp Block.cpp
	g++ -o test SDL_Tetris.cpp Button.cpp Game.cpp Matrix.cpp Shape.cpp TextTexture.cpp Utility.cpp Block.cpp -lSDL2 -lSDL2_ttf -lSDL2_image
